default_context:
  project_name: 'cinema-be'
  project_slug: 'cinema-be'
  domain_main: 'localhost:8080'
  domain_staging: 'stag.localhost:8080'
  docker_swarm_stack_name_main: 'localhost:8080'
  docker_swarm_stack_name_staging: 'stag-localhost:8080'
  secret_key: '2337b843f275bf3a44e1bf5eef12b8ea60b148f30ed85ee50fb12494b157b6b6'
  first_superuser: 'admin@localhost:8080'
  first_superuser_password: 'root'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.localhost:8080", "https://stag.localhost:8080", "https://localhost:8080", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@localhost:8080'
  postgres_password: 'root'
  pgadmin_default_user: 'admin@localhost:8080'
  pgadmin_default_user_password: 'root'
  traefik_constraint_tag: 'localhost:8080'
  traefik_constraint_tag_staging: 'stag.localhost:8080'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:root'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
